### ISSUE TITLE
heap-buffer-overflow detected in function exif_data_load_data of exif-data.c in libexif when running exif with parameter -c

### ISSUE THREAD

**Issue by xiaoxiongwang** [libexif/libexif#28]
Tested in Ubuntu 16.04, 64bit. The tesecase is [here](https://github.com/xiaoxiongwang/security/blob/master/exif(libexif)/exif_heap_buffer_overflow.jpg).

I use the following command:

```shell
./exif -c exif_heap_buffer_overflow.jpg
```

and get:

```
*** Error in `./exif': double free or corruption (!prev): 0x000000000210c6c0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f7b644e37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f7b644ec37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f7b644f053c]
./exif[0x40faf4]
./exif[0x410041]
./exif[0x40660a]
./exif[0x403d4f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f7b6448c830]
./exif[0x404f79]
======= Memory map: ========
00400000-00417000 r-xp 00000000 103:01 21241626                          ./exif
00616000-00617000 r--p 00016000 103:01 21241626                          ./exif
00617000-00618000 rw-p 00017000 103:01 21241626                          ./exif
02108000-02129000 rw-p 00000000 00:00 0                                  [heap]
7f7b5c000000-7f7b5c021000 rw-p 00000000 00:00 0 
7f7b5c021000-7f7b60000000 ---p 00000000 00:00 0 
7f7b63ac2000-7f7b63ad8000 r-xp 00000000 103:01 10490464                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7b63ad8000-7f7b63cd7000 ---p 00016000 103:01 10490464                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7b63cd7000-7f7b63cd8000 rw-p 00015000 103:01 10490464                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7b63cd8000-7f7b64163000 r--p 00000000 103:01 14811834                  /usr/lib/locale/locale-archive
7f7b64163000-7f7b6426b000 r-xp 00000000 103:01 10487658                  /lib/x86_64-linux-gnu/libm-2.23.so
7f7b6426b000-7f7b6446a000 ---p 00108000 103:01 10487658                  /lib/x86_64-linux-gnu/libm-2.23.so
7f7b6446a000-7f7b6446b000 r--p 00107000 103:01 10487658                  /lib/x86_64-linux-gnu/libm-2.23.so
7f7b6446b000-7f7b6446c000 rw-p 00108000 103:01 10487658                  /lib/x86_64-linux-gnu/libm-2.23.so
7f7b6446c000-7f7b6462c000 r-xp 00000000 103:01 10487655                  /lib/x86_64-linux-gnu/libc-2.23.so
7f7b6462c000-7f7b6482c000 ---p 001c0000 103:01 10487655                  /lib/x86_64-linux-gnu/libc-2.23.so
7f7b6482c000-7f7b64830000 r--p 001c0000 103:01 10487655                  /lib/x86_64-linux-gnu/libc-2.23.so
7f7b64830000-7f7b64832000 rw-p 001c4000 103:01 10487655                  /lib/x86_64-linux-gnu/libc-2.23.so
7f7b64832000-7f7b64836000 rw-p 00000000 00:00 0 
7f7b64836000-7f7b64841000 r-xp 00000000 103:01 10490569                  /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f7b64841000-7f7b64a40000 ---p 0000b000 103:01 10490569                  /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f7b64a40000-7f7b64a41000 r--p 0000a000 103:01 10490569                  /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f7b64a41000-7f7b64a42000 rw-p 0000b000 103:01 10490569                  /lib/x86_64-linux-gnu/libpopt.so.0.0.0
7f7b64a42000-7f7b64ab6000 r-xp 00000000 103:01 21241278                  libexif_install/lib/libexif.so.12.3.3
7f7b64ab6000-7f7b64cb6000 ---p 00074000 103:01 21241278                  libexif_install/lib/libexif.so.12.3.3
7f7b64cb6000-7f7b64cc9000 r--p 00074000 103:01 21241278                  libexif_install/lib/libexif.so.12.3.3
7f7b64cc9000-7f7b64cca000 rw-p 00087000 103:01 21241278                  libexif_install/lib/libexif.so.12.3.3
7f7b64cca000-7f7b64cf0000 r-xp 00000000 103:01 10485855                  /lib/x86_64-linux-gnu/ld-2.23.so
7f7b64ebb000-7f7b64ebf000 rw-p 00000000 00:00 0 
7f7b64eed000-7f7b64eef000 rw-p 00000000 00:00 0 
7f7b64eef000-7f7b64ef0000 r--p 00025000 103:01 10485855                  /lib/x86_64-linux-gnu/ld-2.23.so
7f7b64ef0000-7f7b64ef1000 rw-p 00026000 103:01 10485855                  /lib/x86_64-linux-gnu/ld-2.23.so
7f7b64ef1000-7f7b64ef2000 rw-p 00000000 00:00 0 
7ffdf72d0000-7ffdf72f2000 rw-p 00000000 00:00 0                          [stack]
7ffdf7381000-7ffdf7384000 r--p 00000000 00:00 0                          [vvar]
7ffdf7384000-7ffdf7386000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

I use **AddressSanitizer** to build exif and libexif and running it with the following command:

```shell
./exif -c exif_heap_buffer_overflow.jpg
```

This is the ASAN information:

```
=================================================================
==23451==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61200000bd3f at pc 0x7f4e7e0ad676 bp 0x7ffcc91ab730 sp 0x7ffcc91aaed8
READ of size 6 at 0x61200000bd3f thread T0
    #0 0x7f4e7e0ad675 in memcmp (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x77675)
    #1 0x42b4f9 in exif_data_load_data libexif/libexif/exif-data.c:846
    #2 0x42b4f9 in exif_data_new_from_data libexif/libexif/exif-data.c:156
    #3 0x414b1d in jpeg_data_load_data exif/libjpeg/jpeg-data.c:237
    #4 0x4156be in jpeg_data_load_file exif/libjpeg/jpeg-data.c:349
    #5 0x4073f4 in action_save exif/exif/actions.c:168
    #6 0x403d1d in main exif/exif/main.c:484
    #7 0x7f4e7d77782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x4053b8 in _start (./exif+0x4053b8)

0x61200000bd3f is located 1 bytes to the left of 303-byte region [0x61200000bd40,0x61200000be6f)
allocated by thread T0 here:
    #0 0x7f4e7e0ce602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x415503 in jpeg_data_load_file exif/libjpeg/jpeg-data.c:332
    #2 0x4073f4 in action_save exif/exif/actions.c:168
    #3 0x403d1d in main exif/exif/main.c:484
    #4 0x7f4e7d77782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 memcmp
Shadow bytes around the buggy address:
  0x0c247fff9750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff9760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff9770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff9780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff9790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c247fff97a0: fa fa fa fa fa fa fa[fa]00 00 00 00 00 00 00 00
  0x0c247fff97b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fff97c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 07 fa fa
  0x0c247fff97d0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff97e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fff97f0: 00 00 00 00 00 00 00 00 00 00 00 01 fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==23451==ABORTING
```

I use **valgrind** to analysis the bug and get the below information:

```
==23442== Memcheck, a memory error detector
==23442== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==23442== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==23442== Command: ./exif -c ./exif_heap_buffer_overflow.jpg
==23442== 
==23442== Invalid read of size 1
==23442==    at 0x4C33D25: __memcmp_sse4_1 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x4E55093: exif_data_load_data (exif-data.c:846)
==23442==    by 0x4E57147: exif_data_new_from_data (exif-data.c:156)
==23442==    by 0x410CB4: jpeg_data_load_data (jpeg-data.c:237)
==23442==    by 0x411479: jpeg_data_load_file (jpeg-data.c:349)
==23442==    by 0x406565: action_save (actions.c:168)
==23442==    by 0x403D4E: main (main.c:484)
==23442==  Address 0x59acb0f is 1 bytes before a block of size 303 alloc'd
==23442==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x411247: jpeg_data_load_file (jpeg-data.c:332)
==23442==    by 0x406565: action_save (actions.c:168)
==23442==    by 0x403D4E: main (main.c:484)
==23442== 
==23442== Invalid read of size 1
==23442==    at 0x4E5510C: exif_data_load_data (exif-data.c:851)
==23442==    by 0x4E57147: exif_data_new_from_data (exif-data.c:156)
==23442==    by 0x410CB4: jpeg_data_load_data (jpeg-data.c:237)
==23442==    by 0x411479: jpeg_data_load_file (jpeg-data.c:349)
==23442==    by 0x406565: action_save (actions.c:168)
==23442==    by 0x403D4E: main (main.c:484)
==23442==  Address 0x59acb0f is 1 bytes before a block of size 303 alloc'd
==23442==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x411247: jpeg_data_load_file (jpeg-data.c:332)
==23442==    by 0x406565: action_save (actions.c:168)
==23442==    by 0x403D4E: main (main.c:484)
==23442== 
==23442== Invalid free() / delete / delete[] / realloc()
==23442==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x40FAF3: jpeg_data_save_data (jpeg-data.c:154)
==23442==    by 0x410040: jpeg_data_save_file (jpeg-data.c:98)
==23442==    by 0x406609: action_save (actions.c:183)
==23442==    by 0x403D4E: main (main.c:484)
==23442==  Address 0x59adaf0 is 0 bytes inside a block of size 206 free'd
==23442==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x40FAF3: jpeg_data_save_data (jpeg-data.c:154)
==23442==    by 0x410040: jpeg_data_save_file (jpeg-data.c:98)
==23442==    by 0x406609: action_save (actions.c:183)
==23442==    by 0x403D4E: main (main.c:484)
==23442==  Block was alloc'd at
==23442==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23442==    by 0x4E4EFB7: exif_data_save_data_content (exif-data.c:600)
==23442==    by 0x4E503C6: exif_data_save_data_content (exif-data.c:649)
==23442==    by 0x4E534FA: exif_data_save_data (exif-data.c:1028)
==23442==    by 0x40F9B3: jpeg_data_save_data (jpeg-data.c:145)
==23442==    by 0x410040: jpeg_data_save_file (jpeg-data.c:98)
==23442==    by 0x406609: action_save (actions.c:183)
==23442==    by 0x403D4E: main (main.c:484)
==23442== 
Wrote file './exif_heap_buffer_overflow.jpg.modified.jpeg'.
==23442== 
==23442== HEAP SUMMARY:
==23442==     in use at exit: 74 bytes in 1 blocks
==23442==   total heap usage: 213 allocs, 213 frees, 45,045 bytes allocated
==23442== 
==23442== LEAK SUMMARY:
==23442==    definitely lost: 0 bytes in 0 blocks
==23442==    indirectly lost: 0 bytes in 0 blocks
==23442==      possibly lost: 0 bytes in 0 blocks
==23442==    still reachable: 74 bytes in 1 blocks
==23442==         suppressed: 0 bytes in 0 blocks
==23442== Rerun with --leak-check=full to see details of leaked memory
==23442== 
==23442== For counts of detected and suppressed errors, rerun with: -v
==23442== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```

**Comment by msmeissn** [comment]
same as issue !29
