### ISSUE TITLE
【oss-fuzz】Timout in mnote_olympus_entry_get_value

### ISSUE THREAD

**Issue by yangcheng1203** [libexif/libexif#77]
#### Running: fusiontest-testcase-exif_from_data_fuzzer-202108190002
==1723460== ERROR: libFuzzer: timeout after 90 seconds  
    #0 0x52ab01 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3  
    #1 0x4755a8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5  
    #2 0x459669 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5  
    #3 0x7fc511d924bf  (/lib64/libpthread.so.0+0x134bf)  
    #4 0x5369c4 in __sanitizer::internal_strlen(char const*) /src/llvm-project/compiler- rt/lib/sanitizer_common/sanitizer_libc.cpp:167:10  
    #5 0x4c46f5 in printf_common(void*, char const*, __va_list_tag*) /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:496:3  
    #6 0x4c5623 in vsprintf /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1670:1  
    #7 0x4c6733 in sprintf /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1713:1  
    #8 0x57ec46 in mnote_olympus_entry_get_value /src/libexif/libexif/olympus/mnote-olympus-entry.c:818:5  
    #9 0x57c226 in exif_mnote_data_olympus_get_value /src/libexif/libexif/olympus/exif-mnote-data-olympus.c:85:9  
    #10 0x56d1f0 in exif_mnote_data_get_value /src/libexif/libexif/exif-mnote-data.c:148:9  
    #11 0x556040 in mnote_dump(_ExifData*) /src/exif_from_data_fuzzer.cc:29:13  
    #12 0x555e09 in LLVMFuzzerTestOneInput /src/exif_from_data_fuzzer.cc:56:5  
    #13 0x45ae93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15  
    #14 0x446602 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6  
    #15 0x44c2ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9  
    #16 0x475d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10  
    #17 0x7fc511bc3b26 in __libc_start_main (/lib64/libc.so.6+0x25b26)  
    #18 0x4220a9 in _start (/opt/oss-fuzz/build/out/libexif/exif_from_data_fuzzer+0x4220a9)  

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::AlarmCallback()  
SUMMARY: libFuzzer: timeout

**Comment by yangcheng1203** [comment]
libexif fuzz test execution timeout problem：
Perform operation  
./exif_from_data_fuzzer fusiontest-testcase-exif_from_data_fuzzer-202108190002

Software version
libexif：libexif-0_6_22-release

**Comment by yangcheng1203** [comment]
Two problems were also found in the subsequent tests. I am not sure whether it is the problem of the software itself or the oss-fuzz problem.

**Comment by yangcheng1203** [comment]
### Out of memory in exif_data_new_from_data  

#### Running: fusiontest-testcase-exif_from_data_fuzzer-202108190001  
==1697608== ERROR: libFuzzer: out-of-memory (used: 2720Mb; limit: 2048Mb)  
   To change the out-of-memory limit use -rss_limit_mb=<N>  

Live Heap Allocations: 2440207467 bytes in 24188 chunks; quarantined: 47033 bytes in 1187 chunks; 6188 other chunks; total  chunks: 31563; showing top 95% (at most 8 unique contexts)  
2412505155 byte(s) (98%) in 24135 allocation(s)  
    #0 0x522252 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3  
    #1 0x56c7c7 in exif_mem_alloc_func /src/libexif/libexif/exif-mem.c:16:9  
    #2 0x56c646 in exif_mem_alloc /src/libexif/libexif/exif-mem.c:83:28  
    #3 0x57a452 in exif_mnote_data_olympus_load /src/libexif/libexif/olympus/exif-mnote-data-olympus.c:491:30  
    #4 0x56cce7 in exif_mnote_data_load /src/libexif/libexif/exif-mnote-data.c:84:2  
    #5 0x55a317 in interpret_maker_note /src/libexif/libexif/exif-data.c:814:3  
    #6 0x558d96 in exif_data_load_data /src/libexif/libexif/exif-data.c:978:2  
    #7 0x5582dd in exif_data_new_from_data /src/libexif/libexif/exif-data.c:156:2  
    #8 0x555dd2 in LLVMFuzzerTestOneInput /src/exif_from_data_fuzzer.cc:51:16  
    #9 0x45ae93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15  
    #10 0x446602 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6  
    #11 0x44c2ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9  
    #12 0x475d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10  
    #13 0x7f00e90ccb26 in __libc_start_main (/lib64/libc.so.6+0x25b26)  

DEDUP_TOKEN: calloc--exif_mem_alloc_func--exif_mem_alloc  
SUMMARY: libFuzzer: out-of-memory

**Comment by yangcheng1203** [comment]
### Heap-buffer-overflow in exif_mnote_data_olympus_load  
#### Running: fusiontest-testcase-exif_loader_fuzzer-202108190001  
=================================================================  
==1697572==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060000003ba at pc 0x00000057a988 bp 0x7ffc6d7f5660 sp 0x7ffc6d7f5658  
READ of size 1 at 0x6060000003ba thread T0  
SCARINESS: 12 (1-byte-read-heap-buffer-overflow)  
    #0 0x57a987 in exif_mnote_data_olympus_load /src/libexif/libexif/olympus/exif-mnote-data-olympus.c:354:30  
    #1 0x56cc47 in exif_mnote_data_load /src/libexif/libexif/exif-mnote-data.c:84:2  
    #2 0x55a277 in interpret_maker_note /src/libexif/libexif/exif-data.c:814:3  
    #3 0x558cf6 in exif_data_load_data /src/libexif/libexif/exif-data.c:978:2  
    #4 0x56b702 in exif_loader_get_data /src/libexif/libexif/exif-loader.c:401:2  
    #5 0x555eea in LLVMFuzzerTestOneInput /src/exif_loader_fuzzer.cc:63:15  
    #6 0x45ae93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15  
    #7 0x446602 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6  
    #8 0x44c2ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9  
    #9 0x475d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10  
    #10 0x7fb09aa63b26 in __libc_start_main (/lib64/libc.so.6+0x25b26)  
    #11 0x4220a9 in _start (/opt/oss-fuzz/build/out/libexif/exif_loader_fuzzer+0x4220a9)  

DEDUP_TOKEN: exif_mnote_data_olympus_load--exif_mnote_data_load--interpret_maker_note  
0x6060000003ba is located 0 bytes to the right of 58-byte region [0x606000000380,0x6060000003ba)  
allocated by thread T0 here:  
    #0 0x522252 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3  
    #1 0x56c727 in exif_mem_alloc_func /src/libexif/libexif/exif-mem.c:16:9  
    #2 0x56c5a6 in exif_mem_alloc /src/libexif/libexif/exif-mem.c:83:28  
    #3 0x56ba1a in exif_loader_alloc /src/libexif/libexif/exif-loader.c:98:6  
    #4 0x56b010 in exif_loader_copy /src/libexif/libexif/exif-loader.c:140:14  
    #5 0x56ab37 in exif_loader_write /src/libexif/libexif/exif-loader.c:231:9  
    #6 0x555ee2 in LLVMFuzzerTestOneInput /src/exif_loader_fuzzer.cc:62:3  
    #7 0x45ae93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15  
    #8 0x446602 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6  
    #9 0x44c2ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9  
    #10 0x475d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10  
    #11 0x7fb09aa63b26 in __libc_start_main (/lib64/libc.so.6+0x25b26)  

DEDUP_TOKEN: calloc--exif_mem_alloc_func--exif_mem_alloc  
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libexif/libexif/olympus/exif-mnote-data-olympus.c:354:30 in  exif_mnote_data_olympus_load  
Shadow bytes around the buggy address:  
  0x0c0c7fff8020: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00  
  0x0c0c7fff8030: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa  
  0x0c0c7fff8040: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00  
  0x0c0c7fff8050: 00 00 00 02 fa fa fa fa 00 00 00 00 00 00 00 02  
  0x0c0c7fff8060: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa  
=>0x0c0c7fff8070: 00 00 00 00 00 00 00[02]fa fa fa fa 00 00 00 00  
  0x0c0c7fff8080: 00 00 00 00 fa fa fa fa fa fa fa fa fa fa fa fa  
  0x0c0c7fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa  
  0x0c0c7fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa  
  0x0c0c7fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa  
  0x0c0c7fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa  
Shadow byte legend (one shadow byte represents 8 application bytes):  
  Addressable:           00  
  Partially addressable: 01 02 03 04 05 06 07  
  Heap left redzone:       fa  
  Freed heap region:       fd  
  Stack left redzone:      f1  
  Stack mid redzone:       f2  
  Stack right redzone:     f3  
  Stack after return:      f5  
  Stack use after scope:   f8  
  Global redzone:          f9  
  Global init order:       f6  
  Poisoned by user:        f7  
  Container overflow:      fc  
  Array cookie:            ac  
  Intra object redzone:    bb  
  ASan internal:           fe  
  Left alloca redzone:     ca  
  Right alloca redzone:    cb  
  Shadow gap:              cc  
==1697572==ABORTING

**Comment by msmeissn** [comment]
please test against libexif-0_6_23-release

i fixed some timeout issues found by oss-fuzz

**Comment by msmeissn** [comment]
and also attach the data pocs

**Comment by msmeissn** [comment]
e93be918878ab98ee45430858e96cb302ffee2bc should fix fusiontest-testcase-exif_from_data_fuzzer-202108190002

the others I think I have not seen. Please attach the data files.

**Comment by yangcheng1203** [comment]
### Out of memory in exif_data_new_from_data  
Perform operation  
./exif_from_data_fuzzer  fusiontest-testcase-exif_from_data_fuzzer-202108190001  

### Heap-buffer-overflow in exif_mnote_data_olympus_load
Perform operation  
./exif_loader_fuzzer fusiontest-testcase-exif_loader_fuzzer-202108190001

I will provide the test files later

**Comment by yangcheng1203** [comment]
My problem has been solved, thank you
